import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler
import numpy as np

def load_inference_data(filepath):
    """
    Load inference data from a CSV file.
    
    Parameters:
    - filepath: Path to the inference CSV file.
    
    Returns:
    - df: Loaded DataFrame.
    """
    df = pd.read_csv(filepath)
    return df

def preprocess_data(df, scaler_filepath):
    """
    Preprocess the inference data using a previously saved scaler.
    
    Parameters:
    - df: DataFrame containing the inference data.
    - scaler_filepath: Path to the saved scaler file.
    
    Returns:
    - df_scaled: Scaled inference data.
    """
    # Load the saved scaler
    scaler = joblib.load(scaler_filepath)
    
    # Scale the data
    df_scaled = scaler.transform(df)
    return df_scaled

def load_model(model_filepath):
    """
    Load a trained model from a file.
    
    Parameters:
    - model_filepath: Path to the trained model file.
    
    Returns:
    - model: Loaded trained model.
    """
    model = joblib.load(model_filepath)
    return model

def make_predictions(model, df_scaled):
    """
    Make predictions using the trained model on the preprocessed data.
    
    Parameters:
    - model: Trained model.
    - df_scaled: Preprocessed data (scaled).
    
    Returns:
    - predictions: Model predictions.
    """
    predictions = model.predict(df_scaled)
    return predictions

def save_predictions(predictions, output_filepath):
    """
    Save predictions to a CSV file.
    
    Parameters:
    - predictions: Predictions generated by the model.
    - output_filepath: Path to save the predictions CSV file.
    """
    predictions_df = pd.DataFrame(predictions, columns=['Predicted_Price'])
    predictions_df.to_csv(output_filepath, index=False)
    print(f"Predictions saved to {output_filepath}")

def main():
    # Filepaths for the data, scaler, and model
    inference_data_filepath = '../data/testing/inference_data.csv'
    scaler_filepath = '../models/scaler.pkl'
    model_filepath = '../models/notebooks/best_rf_model.pkl'
    
    # Load and preprocess the inference data
    df = load_inference_data(inference_data_filepath)
    df_scaled = preprocess_data(df, scaler_filepath)
    
    # Load the trained model
    model = load_model(model_filepath)
    
    # Make predictions on the new data
    predictions = make_predictions(model, df_scaled)
    
    # Save the predictions to a CSV file
    output_filepath = '../data/predictions/inference_predictions.csv'
    save_predictions(predictions, output_filepath)

if __name__ == '__main__':
    main()
