import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler
import numpy as np

def load_inference_data(filepath):
    """
    Load inference data from a CSV file.
    
    Parameters:
    - filepath: Path to the inference CSV file.
    
    Returns:
    - df: Loaded DataFrame.
    """
    df = pd.read_csv(filepath)
    return df

def preprocess_data(df, scaler_filepath):
    """
    Preprocess the inference data using a previously saved scaler.
    
    Parameters:
    - df: DataFrame containing the inference data.
    - scaler_filepath: Path to the saved scaler file.
    
    Returns:
    - df_scaled: Scaled inference data.
    - df: DataFrame containing the inference data.
    """
    df = df.drop(columns=['last_review', 'listing_url', 'name'])
    scaler = joblib.load(scaler_filepath)
    df_scaled = scaler.transform(df)
    return df_scaled, df

def load_model(model_filepath):
    """
    Load a trained model from a file.
    
    Parameters:
    - model_filepath: Path to the trained model file.
    
    Returns:
    - model: Loaded trained model.
    """
    model = joblib.load(model_filepath)
    return model

def make_predictions(model, df_scaled):
    """
    Make predictions using the trained model on the preprocessed data.
    
    Parameters:
    - model: Trained model.
    - df_scaled: Preprocessed data (scaled).
    
    Returns:
    - predictions: Model predictions.
    """
    predictions = model.predict(df_scaled)
    return predictions

def save_predictions(df, predictions, output_filepath):
    """
    Save predictions to a CSV file.
    
    Parameters:
    - predictions: Predictions generated by the model.
    - output_filepath: Path to save the predictions CSV file.
    """
    df['Predicted_Price'] = predictions
    df.to_csv(output_filepath, index=False)
    print(f"Predictions saved to {output_filepath}")

def main():
    inference_data_filepath = './data/modeling/inference_data.csv'
    scaler_filepath = './models/module/scaler.pkl'
    model_filepath = './models/module/best_rf_model.pkl'
    
    df = load_inference_data(inference_data_filepath)
    df_scaled, df = preprocess_data(df, scaler_filepath)
    
    model = load_model(model_filepath)
    
    predictions = make_predictions(model, df_scaled)
    
    output_filepath = './data/modeling/inference_predictions.csv'
    save_predictions(df, predictions, output_filepath)

if __name__ == '__main__':
    main()
